name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on any tag that starts with v

jobs:
  build-and-release:
    runs-on: macos-latest # Using macOS runner for bottle creation
    permissions:
      contents: write # Needed for creating releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel setuptools twine
          python -m pip install -e .
          
      - name: Build distribution
        run: |
          python -m build
          
      - name: Calculate SHA256
        id: sha
        run: |
          TARBALL_URL="https://github.com/JPC-AV/JPC_AV_videoQC/archive/refs/tags/${GITHUB_REF#refs/tags/}.tar.gz"
          curl -sL $TARBALL_URL -o source.tar.gz
          CHECKSUM=$(shasum -a 256 source.tar.gz | awk '{print $1}')
          echo "sha256=$CHECKSUM" >> $GITHUB_OUTPUT
          
      - name: Build bottle
        run: |
          brew tap JPC-AV/AV-Spex
          brew install --build-bottle --verbose JPC-AV/AV-Spex/av-spex
          brew bottle JPC-AV/AV-Spex/av-spex
          # Rename bottle file to follow naming convention
          mv av-spex--*.bottle.tar.gz av-spex-${GITHUB_REF#refs/tags/v}.arm64_sonoma.bottle.tar.gz
          
      - name: Calculate Bottle SHA256
        id: bottle_sha
        run: |
          BOTTLE_CHECKSUM=$(shasum -a 256 av-spex-${GITHUB_REF#refs/tags/v}.arm64_sonoma.bottle.tar.gz | awk '{print $1}')
          echo "bottle_sha256=$BOTTLE_CHECKSUM" >> $GITHUB_OUTPUT
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            av-spex-*.bottle.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
          
      - name: Trigger Formula Update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: JPC-AV/homebrew-AV-Spex
          event-type: update-formula
          client-payload: '{"tag_name": "${{ github.ref_name }}", "sha256": "${{ steps.sha.outputs.sha256 }}", "bottle_sha256": "${{ steps.bottle_sha.outputs.bottle_sha256 }}"}'